spring:
  application:
    name: proxy-api

logging:
  level:
    root: INFO
    com.proxy.demo: DEBUG
    org.springframework.web: INFO
    org.springframework.boot.actuate: INFO
    io.micrometer: INFO
    io.opentelemetry: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,info,metrics
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
