apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "proxy-api.fullname" . }}
  labels:
    {{- include "proxy-api.labels" . | nindent 4 }}
data:
  SPRING_DATA_REDIS_HOST: {{ .Values.redis.host | quote }}
  SPRING_DATA_REDIS_PORT: {{ .Values.redis.port | quote }}
